/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    'hero-slides': HeroSlide;
    'journey-chapters': JourneyChapter;
    'neden-sultan-items': NedenSultanItem;
    'instagram-posts': InstagramPost;
    branches: Branch;
    news: News;
    events: Event;
    pages: Page;
    staff: Staff;
    'contact-messages': ContactMessage;
    'ik-applications': IkApplication;
    'application-files': ApplicationFile;
    media: Media;
    'media-items': MediaItem;
    'audit-logs': AuditLog;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    'hero-slides': HeroSlidesSelect<false> | HeroSlidesSelect<true>;
    'journey-chapters': JourneyChaptersSelect<false> | JourneyChaptersSelect<true>;
    'neden-sultan-items': NedenSultanItemsSelect<false> | NedenSultanItemsSelect<true>;
    'instagram-posts': InstagramPostsSelect<false> | InstagramPostsSelect<true>;
    branches: BranchesSelect<false> | BranchesSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    staff: StaffSelect<false> | StaffSelect<true>;
    'contact-messages': ContactMessagesSelect<false> | ContactMessagesSelect<true>;
    'ik-applications': IkApplicationsSelect<false> | IkApplicationsSelect<true>;
    'application-files': ApplicationFilesSelect<false> | ApplicationFilesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'media-items': MediaItemsSelect<false> | MediaItemsSelect<true>;
    'audit-logs': AuditLogsSelect<false> | AuditLogsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'ana-sayfa': AnaSayfa;
    'site-ayarlari': SiteAyarlari;
    navigation: Navigation;
  };
  globalsSelect: {
    'ana-sayfa': AnaSayfaSelect<false> | AnaSayfaSelect<true>;
    'site-ayarlari': SiteAyarlariSelect<false> | SiteAyarlariSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-slides".
 */
export interface HeroSlide {
  id: number;
  _order?: string | null;
  tagline: string;
  titleLine1: string;
  titleLine2: string;
  titleLine3: string;
  description: string;
  buttonText: string;
  buttonLink: string;
  slideMedia: {
    kind?: ('image' | 'video') | null;
    media?: (number | null) | Media;
    src?: string | null;
    alt: string;
    poster?: string | null;
  };
  focalPoint?: {
    x?: number | null;
    y?: number | null;
  };
  mediaScale?: number | null;
  mediaAspect?: number | null;
  displayDuration?: number | null;
  /**
   * Kaydı en son güncelleyen panel kullanıcısı.
   */
  lastEditedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * Görsel ve video yüklemeleri — hero, yolculuk, şube galerisi vb.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  /**
   * Medya kütüphanesinde filtreleme için.
   */
  tags?: ('hero' | 'branch' | 'news' | 'event' | 'corporate' | 'video')[] | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Yönetici: tam yetki. Editör: içerik. Gelen kutusu: yalnızca form mesajları.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Yönetici: tam yetki. Editör: içerik. Gelen kutusu: yalnızca iletişim/İK.
   */
  roles: ('admin' | 'editor' | 'inbox')[];
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Ana sayfa Yolculuk bölümü (#yolculuk). Listede sürükle-bırak ile sıralayın.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "journey-chapters".
 */
export interface JourneyChapter {
  id: number;
  _order?: string | null;
  eyebrow: string;
  title: string;
  body: string;
  ctaLabel: string;
  ctaHref: string;
  iconKey: 'palette' | 'book-open-text' | 'compass' | 'flask-conical' | 'sparkles';
  /**
   * Medya yükleyin veya public klasöründeki dosya yolunu girin. Video için poster yolu ekleyin.
   */
  chapterMedia: {
    kind?: ('image' | 'video') | null;
    /**
     * Dosya yüklerseniz aşağıdaki yol alanına gerek kalmaz.
     */
    media?: (number | null) | Media;
    /**
     * Örn. /site-media/IMG-....jpg veya /videos/kademeler.mp4
     */
    src?: string | null;
    alt: string;
    poster?: string | null;
  };
  /**
   * Kaydı en son güncelleyen panel kullanıcısı.
   */
  lastEditedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * Ana sayfa #neden ve kurumsal Neden Sultan sayfası. Sürükle-bırak ile sıralayın.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "neden-sultan-items".
 */
export interface NedenSultanItem {
  id: number;
  _order?: string | null;
  headline: string;
  body: string;
  /**
   * Kaydı en son güncelleyen panel kullanıcısı.
   */
  lastEditedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * Ana sayfa Instagram şeridi (#instagram). Sürükle-bırak ile sıralayın.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "instagram-posts".
 */
export interface InstagramPost {
  id: number;
  _order?: string | null;
  title: string;
  description?: string | null;
  /**
   * Medya yükleyin veya public klasöründeki dosya yolunu girin. Video için poster yolu ekleyin.
   */
  postMedia?: {
    kind?: ('image' | 'video') | null;
    /**
     * Dosya yüklerseniz aşağıdaki yol alanına gerek kalmaz.
     */
    media?: (number | null) | Media;
    /**
     * Örn. /site-media/IMG-....jpg veya /videos/kademeler.mp4
     */
    src?: string | null;
    alt?: string | null;
    poster?: string | null;
  };
  /**
   * Boş bırakılırsa profil adresi kullanılır.
   */
  externalUrl?: string | null;
  /**
   * Kaydı en son güncelleyen panel kullanıcısı.
   */
  lastEditedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * Kampüs sayfaları, iletişim formu, footer ve ana sayfa Okullarımız bölümü (#okullarimiz).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "branches".
 */
export interface Branch {
  id: number;
  /**
   * Yalnızca yönetici yayına alabilir / kaldırabilir.
   */
  isPublished?: boolean | null;
  name: string;
  city: string;
  district: string;
  levels?:
    | {
        level: string;
        id?: string | null;
      }[]
    | null;
  upcoming?: boolean | null;
  address: string;
  phone: string;
  /**
   * Medya yükleyin veya public klasöründeki dosya yolunu girin. Video için poster yolu ekleyin.
   */
  previewMedia?: {
    kind?: ('image' | 'video') | null;
    /**
     * Dosya yüklerseniz aşağıdaki yol alanına gerek kalmaz.
     */
    media?: (number | null) | Media;
    /**
     * Örn. /site-media/IMG-....jpg veya /videos/kademeler.mp4
     */
    src?: string | null;
    alt?: string | null;
    poster?: string | null;
  };
  gallery?:
    | {
        /**
         * Medya yükleyin veya public klasöründeki dosya yolunu girin. Video için poster yolu ekleyin.
         */
        item: {
          kind?: ('image' | 'video') | null;
          /**
           * Dosya yüklerseniz aşağıdaki yol alanına gerek kalmaz.
           */
          media?: (number | null) | Media;
          /**
           * Örn. /site-media/IMG-....jpg veya /videos/kademeler.mp4
           */
          src?: string | null;
          alt: string;
          poster?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Boş bırakılırsa sayfa başlığı kullanılır. Önerilen: en fazla 60 karakter.
   */
  seoTitle?: string | null;
  /**
   * Boş bırakılırsa özet/giriş metni kullanılır. Önerilen: en fazla 155 karakter.
   */
  seoDescription?: string | null;
  /**
   * Sosyal medya ve arama önizlemeleri için görsel.
   */
  ogImage?: (number | null) | Media;
  noIndex?: boolean | null;
  /**
   * Yapay zekâ motorlarının alıntılayabileceği 40–60 kelimelik özet metin.
   */
  geoCitationSummary?: string | null;
  /**
   * Sayfa bazlı soru-cevap çiftleri — FAQPage schema kaynağı.
   */
  faqItems?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Etkinlik filtreleme ve dahili referanslar için.
   */
  slug: string;
  /**
   * Örn. istanbul, kocaeli
   */
  citySlug: string;
  /**
   * Örn. sancaktepe, basiskele
   */
  campusSlug: string;
  /**
   * Kaydı en son güncelleyen panel kullanıcısı.
   */
  lastEditedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * Ana sayfa Güncel bölümü (#guncel) ve /guncel/haberler sayfası.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: number;
  /**
   * Gelecek bir tarih seçilirse kayıt taslakta kalır; zamanı gelince cron ile yayınlanır. Yalnızca yönetici.
   */
  publishAt?: string | null;
  title: string;
  /**
   * Sitede Haberler ve duyurular listesinde filtre için kullanılır.
   */
  kind: 'haber' | 'duyuru';
  date: string;
  /**
   * Liste ve kartlarda görünen kısa metin.
   */
  excerpt: string;
  /**
   * Opsiyonel — ileride haber detay sayfasında kullanılacak.
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  slug?: string | null;
  /**
   * Boş bırakılırsa sayfa başlığı kullanılır. Önerilen: en fazla 60 karakter.
   */
  seoTitle?: string | null;
  /**
   * Boş bırakılırsa özet/giriş metni kullanılır. Önerilen: en fazla 155 karakter.
   */
  seoDescription?: string | null;
  /**
   * Sosyal medya ve arama önizlemeleri için görsel.
   */
  ogImage?: (number | null) | Media;
  noIndex?: boolean | null;
  /**
   * Yapay zekâ motorlarının alıntılayabileceği 40–60 kelimelik özet metin.
   */
  geoCitationSummary?: string | null;
  /**
   * Sayfa bazlı soru-cevap çiftleri — FAQPage schema kaynağı.
   */
  faqItems?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Opsiyonel — liste ve öne çıkan kartlarda kullanılır.
   */
  featuredImage?: (number | null) | Media;
  /**
   * Kaydı en son güncelleyen panel kullanıcısı.
   */
  lastEditedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Ana sayfa Güncel bölümü (#guncel) ve /guncel/etkinlikler sayfası.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  /**
   * Gelecek bir tarih seçilirse kayıt taslakta kalır; zamanı gelince cron ile yayınlanır. Yalnızca yönetici.
   */
  publishAt?: string | null;
  title: string;
  date: string;
  excerpt: string;
  /**
   * Etkinlik detay sayfasında görünür.
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Boş bırakılırsa tüm şubeler için geçerlidir.
   */
  branch?: (number | null) | Branch;
  slug?: string | null;
  /**
   * Boş bırakılırsa sayfa başlığı kullanılır. Önerilen: en fazla 60 karakter.
   */
  seoTitle?: string | null;
  /**
   * Boş bırakılırsa özet/giriş metni kullanılır. Önerilen: en fazla 155 karakter.
   */
  seoDescription?: string | null;
  /**
   * Sosyal medya ve arama önizlemeleri için görsel.
   */
  ogImage?: (number | null) | Media;
  noIndex?: boolean | null;
  /**
   * Yapay zekâ motorlarının alıntılayabileceği 40–60 kelimelik özet metin.
   */
  geoCitationSummary?: string | null;
  /**
   * Sayfa bazlı soru-cevap çiftleri — FAQPage schema kaynağı.
   */
  faqItems?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Opsiyonel — öne çıkan etkinlik kartında kullanılır.
   */
  featuredImage?: (number | null) | Media;
  /**
   * Kaydı en son güncelleyen panel kullanıcısı.
   */
  lastEditedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Site sayfaları — kurumsal, eğitim, rehberlik, yasal. Şablon seçin; sitede ilgili rotada görünür.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  /**
   * Gelecek bir tarih seçilirse kayıt taslakta kalır; zamanı gelince cron ile yayınlanır. Yalnızca yönetici.
   */
  publishAt?: string | null;
  title: string;
  /**
   * URL son segmenti: hakkimizda, anaokulu vb.
   */
  slug: string;
  /**
   * Sayfanın site yolu: /{öneki}/{slug}
   */
  pathPrefix: 'kurumsal' | 'egitim' | 'rehberlik' | 'akademik' | 'yasam' | 'root';
  /**
   * Şablon, sitede hangi düzenin kullanılacağını belirler.
   */
  template: 'kurumsal-blok' | 'overlay-story' | 'egitim-segment' | 'rehberlik' | 'yasal';
  /**
   * Sayfa hero altında görünen kısa açıklama.
   */
  intro?: string | null;
  storyEyebrow?: string | null;
  storyMotto?: string | null;
  storyRows?:
    | {
        eyebrow?: string | null;
        text: string;
        highlights?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  galleryTitle?: string | null;
  galleryDescription?: string | null;
  galleryItems?:
    | {
        /**
         * Medya yükleyin veya public klasöründeki dosya yolunu girin. Video için poster yolu ekleyin.
         */
        item?: {
          kind?: ('image' | 'video') | null;
          /**
           * Dosya yüklerseniz aşağıdaki yol alanına gerek kalmaz.
           */
          media?: (number | null) | Media;
          /**
           * Örn. /site-media/IMG-....jpg veya /videos/kademeler.mp4
           */
          src?: string | null;
          alt?: string | null;
          poster?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Medya yükleyin veya public klasöründeki dosya yolunu girin. Video için poster yolu ekleyin.
   */
  heroMedia?: {
    kind?: ('image' | 'video') | null;
    media?: (number | null) | Media;
    src?: string | null;
    alt?: string | null;
    poster?: string | null;
  };
  sections?:
    | (
        | {
            heading?: string | null;
            /**
             * Örn. kurulus — sayfa içi linkler için.
             */
            anchorId?: string | null;
            paragraphs?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textSection';
          }
        | {
            heading?: string | null;
            items?:
              | {
                  year: string;
                  title: string;
                  detail: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'timelineSection';
          }
        | {
            heading?: string | null;
            note?: string | null;
            cards?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cardGridSection';
          }
        | {
            heading?: string | null;
            body?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'richTextSection';
          }
      )[]
    | null;
  /**
   * Boş bırakılırsa sayfa başlığı kullanılır. Önerilen: en fazla 60 karakter.
   */
  seoTitle?: string | null;
  /**
   * Boş bırakılırsa özet/giriş metni kullanılır. Önerilen: en fazla 155 karakter.
   */
  seoDescription?: string | null;
  /**
   * Sosyal medya ve arama önizlemeleri için görsel.
   */
  ogImage?: (number | null) | Media;
  noIndex?: boolean | null;
  /**
   * Yapay zekâ motorlarının alıntılayabileceği 40–60 kelimelik özet metin.
   */
  geoCitationSummary?: string | null;
  /**
   * Sayfa bazlı soru-cevap çiftleri — FAQPage schema kaynağı.
   */
  faqItems?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Kaydı en son güncelleyen panel kullanıcısı.
   */
  lastEditedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * /kurumsal/idari-kadro sayfasındaki yönetim ve şube kadroları.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "staff".
 */
export interface Staff {
  id: number;
  _order?: string | null;
  /**
   * Yalnızca yönetici yayına alabilir / kaldırabilir.
   */
  isPublished?: boolean | null;
  fullName: string;
  /**
   * Ad Soyad'ın önüne eklenir. Örn: Dr., Prof. Dr., Öğr. Gör. Boş bırakılabilir.
   */
  academicTitle?: string | null;
  title: string;
  /**
   * Örn: X Üniversitesi Y Bölümü Doktorası. Boş bırakılabilir.
   */
  education?: string | null;
  department: 'yonetim' | 'egitim_danisma' | 'egitim' | 'idari';
  /**
   * Yönetim ve Eğitim Danışma Kurulu için boş bırakın.
   */
  branchSlug?: ('sancaktepe' | 'basiskele' | 'serdivan' | 'sincan' | 'mevlana') | null;
  /**
   * Kaydı en son güncelleyen panel kullanıcısı.
   */
  lastEditedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * İletişim sayfası ve ana sayfa Sizi Arayalım modalından gelen mesajlar.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-messages".
 */
export interface ContactMessage {
  id: number;
  name: string;
  email: string;
  phone: string;
  subject: string;
  message: string;
  /**
   * Formda şube seçildiyse.
   */
  branchSlug?: string | null;
  source: 'contact' | 'info_request';
  status: 'new' | 'read' | 'archived';
  updatedAt: string;
  createdAt: string;
}
/**
 * İnsan Kaynakları sayfasından gelen iş başvuruları.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ik-applications".
 */
export interface IkApplication {
  id: number;
  fullName: string;
  email: string;
  phone: string;
  branchSlug?: string | null;
  position: string;
  experienceYears: number;
  education: string;
  coverLetter: string;
  /**
   * PDF veya Word, en fazla 5 MB.
   */
  cv?: (number | null) | ApplicationFile;
  status: 'new' | 'read' | 'archived';
  updatedAt: string;
  createdAt: string;
}
/**
 * İK başvurularına eklenen CV dosyaları (PDF/Word, max 5 MB).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "application-files".
 */
export interface ApplicationFile {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * /guncel/medya sayfası ve ana sayfa medya önizlemesi.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-items".
 */
export interface MediaItem {
  id: number;
  title: string;
  kind: 'foto' | 'video';
  date: string;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Ana sayfa veya arşivde öncelikli gösterim için.
   */
  featured?: boolean | null;
  media: number | Media;
  alt: string;
  caption?: string | null;
  /**
   * Kaydı en son güncelleyen panel kullanıcısı.
   */
  lastEditedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * İçerik değişikliklerinin kim/ne/ne zaman kaydı. Salt okunur.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs".
 */
export interface AuditLog {
  id: number;
  summary: string;
  action: 'create' | 'update' | 'delete';
  collection: string;
  documentId?: string | null;
  userEmail?: string | null;
  userId?: string | null;
  /**
   * Opsiyonel bağlam (ör. _status değişimi).
   */
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'hero-slides';
        value: number | HeroSlide;
      } | null)
    | ({
        relationTo: 'journey-chapters';
        value: number | JourneyChapter;
      } | null)
    | ({
        relationTo: 'neden-sultan-items';
        value: number | NedenSultanItem;
      } | null)
    | ({
        relationTo: 'instagram-posts';
        value: number | InstagramPost;
      } | null)
    | ({
        relationTo: 'branches';
        value: number | Branch;
      } | null)
    | ({
        relationTo: 'news';
        value: number | News;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'staff';
        value: number | Staff;
      } | null)
    | ({
        relationTo: 'contact-messages';
        value: number | ContactMessage;
      } | null)
    | ({
        relationTo: 'ik-applications';
        value: number | IkApplication;
      } | null)
    | ({
        relationTo: 'application-files';
        value: number | ApplicationFile;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'media-items';
        value: number | MediaItem;
      } | null)
    | ({
        relationTo: 'audit-logs';
        value: number | AuditLog;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-slides_select".
 */
export interface HeroSlidesSelect<T extends boolean = true> {
  _order?: T;
  tagline?: T;
  titleLine1?: T;
  titleLine2?: T;
  titleLine3?: T;
  description?: T;
  buttonText?: T;
  buttonLink?: T;
  slideMedia?:
    | T
    | {
        kind?: T;
        media?: T;
        src?: T;
        alt?: T;
        poster?: T;
      };
  focalPoint?:
    | T
    | {
        x?: T;
        y?: T;
      };
  mediaScale?: T;
  mediaAspect?: T;
  displayDuration?: T;
  lastEditedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "journey-chapters_select".
 */
export interface JourneyChaptersSelect<T extends boolean = true> {
  _order?: T;
  eyebrow?: T;
  title?: T;
  body?: T;
  ctaLabel?: T;
  ctaHref?: T;
  iconKey?: T;
  chapterMedia?:
    | T
    | {
        kind?: T;
        media?: T;
        src?: T;
        alt?: T;
        poster?: T;
      };
  lastEditedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "neden-sultan-items_select".
 */
export interface NedenSultanItemsSelect<T extends boolean = true> {
  _order?: T;
  headline?: T;
  body?: T;
  lastEditedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "instagram-posts_select".
 */
export interface InstagramPostsSelect<T extends boolean = true> {
  _order?: T;
  title?: T;
  description?: T;
  postMedia?:
    | T
    | {
        kind?: T;
        media?: T;
        src?: T;
        alt?: T;
        poster?: T;
      };
  externalUrl?: T;
  lastEditedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "branches_select".
 */
export interface BranchesSelect<T extends boolean = true> {
  isPublished?: T;
  name?: T;
  city?: T;
  district?: T;
  levels?:
    | T
    | {
        level?: T;
        id?: T;
      };
  upcoming?: T;
  address?: T;
  phone?: T;
  previewMedia?:
    | T
    | {
        kind?: T;
        media?: T;
        src?: T;
        alt?: T;
        poster?: T;
      };
  gallery?:
    | T
    | {
        item?:
          | T
          | {
              kind?: T;
              media?: T;
              src?: T;
              alt?: T;
              poster?: T;
            };
        id?: T;
      };
  seoTitle?: T;
  seoDescription?: T;
  ogImage?: T;
  noIndex?: T;
  geoCitationSummary?: T;
  faqItems?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  slug?: T;
  citySlug?: T;
  campusSlug?: T;
  lastEditedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  publishAt?: T;
  title?: T;
  kind?: T;
  date?: T;
  excerpt?: T;
  body?: T;
  slug?: T;
  seoTitle?: T;
  seoDescription?: T;
  ogImage?: T;
  noIndex?: T;
  geoCitationSummary?: T;
  faqItems?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  featuredImage?: T;
  lastEditedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  publishAt?: T;
  title?: T;
  date?: T;
  excerpt?: T;
  body?: T;
  branch?: T;
  slug?: T;
  seoTitle?: T;
  seoDescription?: T;
  ogImage?: T;
  noIndex?: T;
  geoCitationSummary?: T;
  faqItems?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  featuredImage?: T;
  lastEditedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  publishAt?: T;
  title?: T;
  slug?: T;
  pathPrefix?: T;
  template?: T;
  intro?: T;
  storyEyebrow?: T;
  storyMotto?: T;
  storyRows?:
    | T
    | {
        eyebrow?: T;
        text?: T;
        highlights?:
          | T
          | {
              text?: T;
              id?: T;
            };
        id?: T;
      };
  galleryTitle?: T;
  galleryDescription?: T;
  galleryItems?:
    | T
    | {
        item?:
          | T
          | {
              kind?: T;
              media?: T;
              src?: T;
              alt?: T;
              poster?: T;
            };
        id?: T;
      };
  heroMedia?:
    | T
    | {
        kind?: T;
        media?: T;
        src?: T;
        alt?: T;
        poster?: T;
      };
  sections?:
    | T
    | {
        textSection?:
          | T
          | {
              heading?: T;
              anchorId?: T;
              paragraphs?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        timelineSection?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    year?: T;
                    title?: T;
                    detail?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        cardGridSection?:
          | T
          | {
              heading?: T;
              note?: T;
              cards?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        richTextSection?:
          | T
          | {
              heading?: T;
              body?: T;
              id?: T;
              blockName?: T;
            };
      };
  seoTitle?: T;
  seoDescription?: T;
  ogImage?: T;
  noIndex?: T;
  geoCitationSummary?: T;
  faqItems?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  lastEditedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "staff_select".
 */
export interface StaffSelect<T extends boolean = true> {
  _order?: T;
  isPublished?: T;
  fullName?: T;
  academicTitle?: T;
  title?: T;
  education?: T;
  department?: T;
  branchSlug?: T;
  lastEditedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-messages_select".
 */
export interface ContactMessagesSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  subject?: T;
  message?: T;
  branchSlug?: T;
  source?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ik-applications_select".
 */
export interface IkApplicationsSelect<T extends boolean = true> {
  fullName?: T;
  email?: T;
  phone?: T;
  branchSlug?: T;
  position?: T;
  experienceYears?: T;
  education?: T;
  coverLetter?: T;
  cv?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "application-files_select".
 */
export interface ApplicationFilesSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  tags?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-items_select".
 */
export interface MediaItemsSelect<T extends boolean = true> {
  title?: T;
  kind?: T;
  date?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  featured?: T;
  media?: T;
  alt?: T;
  caption?: T;
  lastEditedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs_select".
 */
export interface AuditLogsSelect<T extends boolean = true> {
  summary?: T;
  action?: T;
  collection?: T;
  documentId?: T;
  userEmail?: T;
  userId?: T;
  meta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Ana sayfadaki sabit bölüm başlıkları, metinler ve medya ayarları. Tekrarlayan içerik (slaytlar, yolculuk vb.) ilgili koleksiyonlardan yönetilir.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ana-sayfa".
 */
export interface AnaSayfa {
  id: number;
  mission: {
    tagline: string;
    titleLine1: string;
    titleLine2: string;
    titleLine3?: string | null;
    description: string;
    secondaryDescription?: string | null;
    levels?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
    decorMedia?:
      | {
          /**
           * Medya yükleyin veya public klasöründeki dosya yolunu girin. Video için poster yolu ekleyin.
           */
          media?: {
            kind?: ('image' | 'video') | null;
            /**
             * Dosya yüklerseniz aşağıdaki yol alanına gerek kalmaz.
             */
            media?: (number | null) | Media;
            /**
             * Örn. /site-media/IMG-....jpg veya /videos/kademeler.mp4
             */
            src?: string | null;
            alt?: string | null;
            poster?: string | null;
          };
          id?: string | null;
        }[]
      | null;
  };
  journey: {
    headline: string;
  };
  neden: {
    eyebrow: string;
    title: string;
    /**
     * Örn. "Sultan Okulları?" — yeşil renkte gösterilir.
     */
    titleHighlight?: string | null;
    description: string;
    ctaLabel: string;
    ctaHref: string;
    marqueeValues?:
      | {
          value: string;
          id?: string | null;
        }[]
      | null;
  };
  videoSection: {
    eyebrow: string;
    title: string;
    description: string;
    ctaLabel: string;
    ctaHref: string;
    /**
     * Medya yükleyin veya public klasöründeki dosya yolunu girin. Video için poster yolu ekleyin.
     */
    featuredVideo: {
      kind?: ('image' | 'video') | null;
      /**
       * Dosya yüklerseniz aşağıdaki yol alanına gerek kalmaz.
       */
      media?: (number | null) | Media;
      /**
       * Örn. /site-media/IMG-....jpg veya /videos/kademeler.mp4
       */
      src?: string | null;
      alt: string;
      poster?: string | null;
    };
  };
  branchesSection: {
    eyebrow: string;
    title: string;
    description: string;
    ctaLabel: string;
    ctaHref: string;
  };
  guncelSection: {
    eyebrow: string;
    title: string;
    description: string;
    ctaLabel: string;
    ctaHref: string;
    featuredEventLabel?: string | null;
    upcomingEventsLabel?: string | null;
    newsLabel?: string | null;
    /**
     * Medya yükleyin veya public klasöründeki dosya yolunu girin. Video için poster yolu ekleyin.
     */
    featuredEventMedia?: {
      kind?: ('image' | 'video') | null;
      /**
       * Dosya yüklerseniz aşağıdaki yol alanına gerek kalmaz.
       */
      media?: (number | null) | Media;
      /**
       * Örn. /site-media/IMG-....jpg veya /videos/kademeler.mp4
       */
      src?: string | null;
      alt?: string | null;
      poster?: string | null;
    };
  };
  instagramSection: {
    eyebrow: string;
    title: string;
    description: string;
    handle: string;
    profileUrl: string;
  };
  quickLinksSection: {
    eyebrow: string;
    title: string;
    description: string;
    links?:
      | {
          href: string;
          label: string;
          description: string;
          iconKey:
            | 'book-open'
            | 'graduation-cap'
            | 'palette'
            | 'hand-heart'
            | 'heart-handshake'
            | 'sprout'
            | 'radio'
            | 'phone'
            | 'book-open-text'
            | 'compass'
            | 'flask-conical'
            | 'sparkles';
          id?: string | null;
        }[]
      | null;
  };
  yemekhaneSection?: {
    paragraphs?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Medya yükleyin veya public klasöründeki dosya yolunu girin. Video için poster yolu ekleyin.
     */
    media?: {
      kind?: ('image' | 'video') | null;
      /**
       * Dosya yüklerseniz aşağıdaki yol alanına gerek kalmaz.
       */
      media?: (number | null) | Media;
      /**
       * Örn. /site-media/IMG-....jpg veya /videos/kademeler.mp4
       */
      src?: string | null;
      alt?: string | null;
      poster?: string | null;
    };
  };
  infoModal: {
    enabled?: boolean | null;
    brandLabel?: string | null;
    title: string;
    subtitle: string;
    submitLabel: string;
    dismissLabel?: string | null;
    kvkkText?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Footer, sosyal medya ve genel iletişim bilgileri — footer ve /iletisim sayfasını etkiler. Yalnızca yönetici güncelleyebilir.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-ayarlari".
 */
export interface SiteAyarlari {
  id: number;
  instagramHandle?: string | null;
  instagramUrl?: string | null;
  footerEmail?: string | null;
  footerPhone?: string | null;
  socialLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Sayfa özel görseli yoksa sosyal medya önizlemesinde kullanılır.
   */
  defaultOgImage?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Üst menü yönetimi. Bölümler doluysa kod içi menünün yerine geçer; boşsa kod menüsü + ek linkler kullanılır. Yalnızca yönetici.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  /**
   * Açıkken aşağıdaki menü bölümleri site üst menüsünün kaynağı olur.
   */
  useCmsMenu?: boolean | null;
  /**
   * Her bölüm bir üst menü başlığıdır (Kurumsal, Eğitim…).
   */
  sections?:
    | {
        /**
         * Benzersiz slug — örn. kurumsal, egitim
         */
        key: string;
        label: string;
        description?: string | null;
        items?:
          | {
              label: string;
              /**
               * Örn. /egitim/anaokulu
               */
              href: string;
              /**
               * Opsiyonel — örn. BookOpen, Compass
               */
              icon?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * CMS menüsü kapalıyken kod menüsüne eklenir. CMS menüsü açıkken ilgili bölüme eklenmez — bölüm items kullanın.
   */
  extraLinks?:
    | {
        label: string;
        /**
         * Örn. /egitim/anaokulu
         */
        href: string;
        /**
         * Opsiyonel — örn. BookOpen, Compass
         */
        icon?: string | null;
        group?: ('kurumsal' | 'egitim' | 'akademik' | 'rehberlik' | 'okullar' | 'yasam' | 'guncel') | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ana-sayfa_select".
 */
export interface AnaSayfaSelect<T extends boolean = true> {
  mission?:
    | T
    | {
        tagline?: T;
        titleLine1?: T;
        titleLine2?: T;
        titleLine3?: T;
        description?: T;
        secondaryDescription?: T;
        levels?:
          | T
          | {
              label?: T;
              id?: T;
            };
        decorMedia?:
          | T
          | {
              media?:
                | T
                | {
                    kind?: T;
                    media?: T;
                    src?: T;
                    alt?: T;
                    poster?: T;
                  };
              id?: T;
            };
      };
  journey?:
    | T
    | {
        headline?: T;
      };
  neden?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        titleHighlight?: T;
        description?: T;
        ctaLabel?: T;
        ctaHref?: T;
        marqueeValues?:
          | T
          | {
              value?: T;
              id?: T;
            };
      };
  videoSection?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
        ctaLabel?: T;
        ctaHref?: T;
        featuredVideo?:
          | T
          | {
              kind?: T;
              media?: T;
              src?: T;
              alt?: T;
              poster?: T;
            };
      };
  branchesSection?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
        ctaLabel?: T;
        ctaHref?: T;
      };
  guncelSection?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
        ctaLabel?: T;
        ctaHref?: T;
        featuredEventLabel?: T;
        upcomingEventsLabel?: T;
        newsLabel?: T;
        featuredEventMedia?:
          | T
          | {
              kind?: T;
              media?: T;
              src?: T;
              alt?: T;
              poster?: T;
            };
      };
  instagramSection?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
        handle?: T;
        profileUrl?: T;
      };
  quickLinksSection?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
        links?:
          | T
          | {
              href?: T;
              label?: T;
              description?: T;
              iconKey?: T;
              id?: T;
            };
      };
  yemekhaneSection?:
    | T
    | {
        paragraphs?:
          | T
          | {
              text?: T;
              id?: T;
            };
        media?:
          | T
          | {
              kind?: T;
              media?: T;
              src?: T;
              alt?: T;
              poster?: T;
            };
      };
  infoModal?:
    | T
    | {
        enabled?: T;
        brandLabel?: T;
        title?: T;
        subtitle?: T;
        submitLabel?: T;
        dismissLabel?: T;
        kvkkText?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-ayarlari_select".
 */
export interface SiteAyarlariSelect<T extends boolean = true> {
  instagramHandle?: T;
  instagramUrl?: T;
  footerEmail?: T;
  footerPhone?: T;
  socialLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  defaultOgImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  useCmsMenu?: T;
  sections?:
    | T
    | {
        key?: T;
        label?: T;
        description?: T;
        items?:
          | T
          | {
              label?: T;
              href?: T;
              icon?: T;
              id?: T;
            };
        id?: T;
      };
  extraLinks?:
    | T
    | {
        label?: T;
        href?: T;
        icon?: T;
        group?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}